server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /customer-ms
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
io:
  reflectoring:
    kafka:
      bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
application:
  activation:
    url: ${SERVER_HOST}:${SERVER_PORT}/customer-ms/api/v1/customer/activate/
